"""add policy table and link exclusion to policy

Revision ID: 038422a21243
Revises: 6db6c59cfdb6
Create Date: 2026-03-11 22:49:56.120493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '038422a21243'
down_revision = '6db6c59cfdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('exclusion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'policy', ['policy_id'], ['id'])
        batch_op.drop_column('policy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exclusion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('policy_id')

    op.drop_table('policy')
    # ### end Alembic commands ###
