"""add exclusions

Revision ID: a215842f1bdd
Revises: d23fc46246aa
Create Date: 2026-02-20 13:48:50.917474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a215842f1bdd'
down_revision = 'd23fc46246aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('excluded_email', sa.String(length=254), nullable=False),
    sa.Column('until', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exclusion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exclusion_excluded_email'), ['excluded_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exclusion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exclusion_excluded_email'))

    op.drop_table('exclusion')
    # ### end Alembic commands ###
