"""test migration

Revision ID: cc4657bd0654
Revises: 038422a21243
Create Date: 2026-03-11 23:23:36.478046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4657bd0654'
down_revision = '038422a21243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exclusion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'policy', ['policy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exclusion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
