"""add policy to exclusion

Revision ID: f4e62e8bd11b
Revises: 6e2da5c76e1b
Create Date: 2026-03-06 20:11:30.125762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e62e8bd11b'
down_revision = '6e2da5c76e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exclusion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exclusion', schema=None) as batch_op:
        batch_op.drop_column('policy')

    # ### end Alembic commands ###
